# Site settings
title: y-array
email: 08to09@@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Technical remindings & thoughts
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yarray.github.io" # the base hostname & protocol for your site
github_username:  yarray

# Build settings
markdown: kramdown
